version: "3"
services:
  install_package:
    image: "node:10.23"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm install"

  build:
    image: "node:10.23"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm run-script build"

  start:
    image: "node:10.23"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "127.0.0.1:8888:3001"
    command: "npm run-script start"
    stdin_open: true

  ide:
    image: "theiaide/theia"
    volumes:
      - ./:/home/project
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8888:3001"
